#ARG version="3.6-alpine"
ARG version="alpine:lts"
FROM python
LABEL maintainer="frederic-bougrier"

WORKDIR /opt/
RUN apt-get update \
    && apt-get install --no-install-recommends -y git \
    #&& git clone https://github.com/eazytraining/projet-fils-rouge.git /opt/ \
    && git clone https://github.com/frederic-bougrier/projet-fil-rouge.git /opt/ \
    && apt-get clean \
    && rm -rf /var/lib/apt/list/* \
    && rm -rf jenkins-tools releases-txt README.md *pdf \
    && pip3 install flask

ENV ODOO_URL='https://www.odoo.com/' 
ENV PGADMIN_URL='https://www.pgadmin.org'

EXPOSE 8080
ENTRYPOINT ["python", "app.py"]

