apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-cm
  labels:
    env: prod
    app: pgadmin
data:
  servers.json: |
    {
    "Servers": {
        "1": {
          "Name": "devobs project",
          "Group": "Database group",
          "Port": 5432,
          "Host":"postgres-svc",
          "SSLMode":"prefer",
          "MaintenanceDB":"postgres"
        }
      }
    }
  email: toto@toto.com

#"Username": "odoo",
#"Password": "myodoo",