apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-webapp-deploy
  labels:
    env: prod 
    app: ic-webapp
spec:
  selector:
    matchLabels:
      app: ic-webapp
  template:
    metadata:
      labels:
        app: ic-webapp
    spec:
      containers:
      - name: ic-webapp
        image: ulrichsteve/ic-webapp:1.0
        env:
        - name: ODOO_URL 
          valueFrom: 
            configMapKeyRef:
              key: ODOO_URL 
              name: ic-webapp-cm
        - name: PGADMIN_URL 
          valueFrom:
            configMapKeyRef:
              key: PGADMIN_URL 
              name: ic-webapp-cm
        ports:
        - containerPort: 8080

