apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    env: prod
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: database 
              name: postgres-cm
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password 
              name: postgres-secret
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: user 
              name: postgres-cm
        ports:
        - containerPort: 5432
#!!!!!!!!!!!
 #       volumeMounts:
 #       - name: postgres-storage
 #         mountPath: /var/lib/postgresql/data/pgdata
 #     volumes:
 #     - name: postgres-storage
 #       persistentVolumeClaim:
 #         claimName: postgres-pvc
#!!!!!!!!!!!

