apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret 
  labels: 
    env: prod 
    app: postgres
type: Opaque
data:
  # Même mot de pass dans odoo-secret.yml (base64)
  # CAD : echo -n "myodoo" | base64
  password: bXlvZG9v

